// src/lib/db/schema.ts — the canonical OotaOS schema. Copy verbatim.
// Every table here has a corresponding migration generated by drizzle-kit.
// Do NOT add tables without updating SKILL.md §4 first.

import {
  bigint,
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
  vector,
} from 'drizzle-orm/pg-core';

const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return 'bytea';
  },
});

// ── Enums ────────────────────────────────────────────────────────────────
export const userRoleEnum = pgEnum('user_role', ['founder', 'team', 'advisor']);

export const firmTypeEnum = pgEnum('firm_type', [
  'vc',
  'cvc',
  'angel',
  'family_office',
  'accelerator',
  'syndicate',
]);

export const stageEnum = pgEnum('lead_stage', [
  'prospect',
  'contacted',
  'engaged',
  'nda_pending',
  'nda_signed',
  'meeting_scheduled',
  'diligence',
  'term_sheet',
  'funded',
  'closed_lost',
]);

export const interactionKindEnum = pgEnum('interaction_kind', [
  'page_view',
  'question_asked',
  'email_sent',
  'email_received',
  'document_viewed',
  'meeting_held',
  'note',
  'stage_change',
  'email_verified',
]);

export const documentKindEnum = pgEnum('document_kind', [
  'pitch_deck',
  'financial_model',
  'customer_refs',
  'tech_arch',
  'cap_table',
  'product_demo',
  'term_sheet',
  'other',
]);

export const watermarkPolicyEnum = pgEnum('watermark_policy', ['per_investor', 'static', 'none']);

export const aiAgentEnum = pgEnum('ai_agent', ['concierge', 'drafter', 'strategist', 'curator']);

export const aiOutcomeEnum = pgEnum('ai_outcome', ['ok', 'refused', 'error', 'injected']);

export const emailOutboxStatusEnum = pgEnum('email_outbox_status', [
  'draft',
  'approved',
  'queued',
  'sent',
  'bounced',
  'failed',
  'cancelled',
]);

// ── Workspaces ───────────────────────────────────────────────────────────
export const workspaces = pgTable('workspaces', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  aiEnabled: boolean('ai_enabled').notNull().default(true),
  aiMonthlyCapUsd: integer('ai_monthly_cap_usd').notNull().default(50),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Users ────────────────────────────────────────────────────────────────
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    email: varchar('email', { length: 254 }).notNull(),
    passwordHash: text('password_hash').notNull(),
    totpSecret: text('totp_secret').notNull(),
    role: userRoleEnum('role').notNull(),
    displayName: text('display_name'),
    whatsappE164: text('whatsapp_e164'),
    publicEmail: text('public_email'),
    signatureMarkdown: text('signature_markdown'),
    companyName: text('company_name'),
    companyWebsite: text('company_website'),
    companyAddress: text('company_address'),
    logoUrl: text('logo_url'),
    avatarUrl: text('avatar_url'),
    defaultTimezone: text('default_timezone'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    emailUnique: uniqueIndex('users_workspace_email_idx').on(t.workspaceId, t.email),
  }),
);

// ── Sessions (Lucia) ─────────────────────────────────────────────────────
export const sessions = pgTable('sessions', {
  id: text('id').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
});

// ── Firms ────────────────────────────────────────────────────────────────
export const firms = pgTable(
  'firms',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    firmType: firmTypeEnum('firm_type').notNull(),
    website: text('website'),
    hqCity: text('hq_city'),
    hqCountry: text('hq_country'),
    aumUsd: bigint('aum_usd', { mode: 'number' }),
    activeFund: text('active_fund'),
    fundSizeUsd: bigint('fund_size_usd', { mode: 'number' }),
    stageFocus: text('stage_focus').array(),
    sectorFocus: text('sector_focus').array(),
    geographyFocus: text('geography_focus').array(),
    chequeMinUsd: bigint('cheque_min_usd', { mode: 'number' }),
    chequeMaxUsd: bigint('cheque_max_usd', { mode: 'number' }),
    leadFollow: text('lead_follow'),
    boardSeatPolicy: text('board_seat_policy'),
    portfolioCount: integer('portfolio_count'),
    notablePortfolio: text('notable_portfolio').array(),
    competitorPortfolio: text('competitor_portfolio').array(),
    recentInvestments: jsonb('recent_investments'),
    notableExits: text('notable_exits').array(),
    decisionSpeed: text('decision_speed'),
    logoUrl: text('logo_url'),
    foundedYear: integer('founded_year'),
    twitterHandle: text('twitter_handle'),
    linkedinUrl: text('linkedin_url'),
    tracxnUrl: text('tracxn_url'),
    topSectorsInPortfolio: text('top_sectors_in_portfolio').array(),
    topLocationsInPortfolio: text('top_locations_in_portfolio').array(),
    topEntryRounds: text('top_entry_rounds').array(),
    dealsLast12Months: integer('deals_last_12_months'),
    // ── Richer Tracxn signals (v1.1 of curator/tracxn-parse prompt) ───────
    tracxnScore: integer('tracxn_score'),
    medianPortfolioTracxnScore: integer('median_portfolio_tracxn_score'),
    portfolioIpos: integer('portfolio_ipos'),
    portfolioAcquisitions: integer('portfolio_acquisitions'),
    portfolioUnicorns: integer('portfolio_unicorns'),
    portfolioSoonicorns: integer('portfolio_soonicorns'),
    teamSizeTotal: integer('team_size_total'),
    fundClassification: text('fund_classification').array(),
    operatingLocation: text('operating_location'),
    stageDistribution: jsonb('stage_distribution'),
    sectorDistribution: jsonb('sector_distribution'),
    locationDistribution: jsonb('location_distribution'),
    specialFlags: text('special_flags').array(),
    recentDeals: jsonb('recent_deals'),
    keyPeople: jsonb('key_people'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    nameIdx: index('firms_workspace_name_idx').on(t.workspaceId, t.name),
  }),
);

// ── Investors ────────────────────────────────────────────────────────────
export const investors = pgTable(
  'investors',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    firmId: uuid('firm_id')
      .notNull()
      .references(() => firms.id, { onDelete: 'cascade' }),
    firstName: text('first_name').notNull(),
    lastName: text('last_name').notNull(),
    title: text('title').notNull(),
    decisionAuthority: text('decision_authority').notNull(),
    email: varchar('email', { length: 254 }).notNull(),
    mobileE164: text('mobile_e164'),
    linkedinUrl: text('linkedin_url'),
    twitterHandle: text('twitter_handle'),
    introPath: text('intro_path'),
    timezone: text('timezone').notNull(),
    preferredMeetingHours: text('preferred_meeting_hours'),
    priorCompany: text('prior_company'),
    mutualConnections: text('mutual_connections').array(),
    personalThesisNotes: text('personal_thesis_notes'),
    photoUrl: text('photo_url'),
    city: text('city'),
    country: text('country'),
    crunchbaseUrl: text('crunchbase_url'),
    tracxnUrl: text('tracxn_url'),
    angellistUrl: text('angellist_url'),
    websiteUrl: text('website_url'),
    checkSizeMinUsd: bigint('check_size_min_usd', { mode: 'number' }),
    checkSizeMaxUsd: bigint('check_size_max_usd', { mode: 'number' }),
    sectorInterests: text('sector_interests').array(),
    stageInterests: text('stage_interests').array(),
    pastInvestments: jsonb('past_investments'),
    bioSummary: text('bio_summary'),
    warmthScore: integer('warmth_score'),
    lastContactAt: timestamp('last_contact_at', { withTimezone: true }),
    nextReminderAt: timestamp('next_reminder_at', { withTimezone: true }),
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
    interests: jsonb('interests'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    emailUnique: uniqueIndex('investors_workspace_email_idx').on(t.workspaceId, t.email),
  }),
);

// ── Deals ────────────────────────────────────────────────────────────────
export const deals = pgTable('deals', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspaceId: uuid('workspace_id')
    .notNull()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  roundLabel: text('round_label').notNull(),
  targetSizeUsd: bigint('target_size_usd', { mode: 'number' }).notNull(),
  preMoneyUsd: bigint('pre_money_usd', { mode: 'number' }),
  postMoneyUsd: bigint('post_money_usd', { mode: 'number' }),
  committedUsd: bigint('committed_usd', { mode: 'number' }).notNull().default(0),
  seedFunded: boolean('seed_funded').notNull().default(false),
  companyType: text('company_type').notNull(),
  incorporationCountry: text('incorporation_country').notNull(),
  pitchJurisdiction: text('pitch_jurisdiction').notNull(),
  closeDate: timestamp('close_date', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Leads ────────────────────────────────────────────────────────────────
export const leads = pgTable(
  'leads',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    dealId: uuid('deal_id')
      .notNull()
      .references(() => deals.id, { onDelete: 'cascade' }),
    investorId: uuid('investor_id')
      .notNull()
      .references(() => investors.id, { onDelete: 'cascade' }),
    stage: stageEnum('stage').notNull().default('prospect'),
    stageEnteredAt: timestamp('stage_entered_at', { withTimezone: true }).notNull().defaultNow(),
    nextActionOwner: text('next_action_owner'),
    nextActionDue: timestamp('next_action_due', { withTimezone: true }),
    sourceOfLead: text('source_of_lead'),
    referrerName: text('referrer_name'),
    thesisFitScore: integer('thesis_fit_score'),
    internalNotes: text('internal_notes'),
    askUsd: bigint('ask_usd', { mode: 'number' }),
    offerTerms: jsonb('offer_terms'),
    // ── Relationship-state fields (moved from investors in the fundraising-OS refactor) ──
    warmthScore: integer('warmth_score'),
    introPath: text('intro_path'),
    lastContactAt: timestamp('last_contact_at', { withTimezone: true }),
    closedLostReason: text('closed_lost_reason'),
    fundedAmountUsd: bigint('funded_amount_usd', { mode: 'number' }),
    fundedAt: timestamp('funded_at', { withTimezone: true }),
    committedUsd: bigint('committed_usd', { mode: 'number' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    pipelineIdx: index('leads_pipeline_idx').on(t.workspaceId, t.stage, t.updatedAt),
  }),
);

// ── Interactions ─────────────────────────────────────────────────────────
export const interactions = pgTable(
  'interactions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'cascade' }),
    investorId: uuid('investor_id').references(() => investors.id, { onDelete: 'cascade' }),
    kind: interactionKindEnum('kind').notNull(),
    payload: jsonb('payload').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    timelineIdx: index('interactions_timeline_idx').on(t.leadId, t.createdAt),
    investorTimelineIdx: index('interactions_investor_timeline_idx').on(t.investorId, t.createdAt),
  }),
);

// ── Documents ────────────────────────────────────────────────────────────
export const documents = pgTable('documents', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspaceId: uuid('workspace_id')
    .notNull()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  // Deal-scoping (rule #9). Nullable during transition; new uploads must set it.
  dealId: uuid('deal_id').references(() => deals.id),
  kind: documentKindEnum('kind').notNull(),
  title: text('title'),
  r2Key: text('r2_key').notNull(),
  originalFilename: text('original_filename').notNull(),
  mimeType: text('mime_type').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  sha256: text('sha256').notNull(),
  watermarkPolicy: watermarkPolicyEnum('watermark_policy').notNull().default('per_investor'),
  // Per-stage permissioning (rule #10). NULL = visible to any cookie-validated investor.
  minLeadStage: stageEnum('min_lead_stage'),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  uploadedBy: uuid('uploaded_by')
    .notNull()
    .references(() => users.id),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Document Versions ────────────────────────────────────────────────────
// Every time a document is replaced, the previous row's bytes + metadata
// are archived here so the founder can audit what was shared with whom.
export const documentVersions = pgTable(
  'document_versions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    documentId: uuid('document_id')
      .notNull()
      .references(() => documents.id, { onDelete: 'cascade' }),
    version: integer('version').notNull(),
    kind: documentKindEnum('kind').notNull(),
    originalFilename: text('original_filename').notNull(),
    mimeType: text('mime_type').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    r2Key: text('r2_key').notNull(),
    sha256: text('sha256').notNull(),
    minLeadStage: stageEnum('min_lead_stage'),
    dealId: uuid('deal_id'),
    archivedAt: timestamp('archived_at', { withTimezone: true }).notNull().defaultNow(),
    archivedBy: uuid('archived_by').references(() => users.id),
  },
  (t) => ({
    lookupIdx: index('document_versions_workspace_doc_idx').on(
      t.workspaceId,
      t.documentId,
      t.version,
    ),
  }),
);

// ── Share Links ──────────────────────────────────────────────────────────
export const shareLinks = pgTable(
  'share_links',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'cascade' }),
    documentId: uuid('document_id')
      .notNull()
      .references(() => documents.id, { onDelete: 'cascade' }),
    token: text('token').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    downloadAllowed: boolean('download_allowed').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tokenUnique: uniqueIndex('share_links_token_idx').on(t.token),
  }),
);

// ── NDAs ─────────────────────────────────────────────────────────────────
export const ndas = pgTable('ndas', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspaceId: uuid('workspace_id')
    .notNull()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  leadId: uuid('lead_id')
    .notNull()
    .references(() => leads.id, { onDelete: 'cascade' }),
  templateVersion: text('template_version').notNull(),
  signedPdfR2Key: text('signed_pdf_r2_key').notNull(),
  signedPdfSha256: text('signed_pdf_sha256').notNull(),
  signerName: text('signer_name').notNull(),
  signerTitle: text('signer_title').notNull(),
  signerFirm: text('signer_firm').notNull(),
  signerEmail: text('signer_email').notNull(),
  signerIp: text('signer_ip').notNull(),
  signerUserAgent: text('signer_user_agent').notNull(),
  otpVerifiedAt: timestamp('otp_verified_at', { withTimezone: true }).notNull(),
  signedAt: timestamp('signed_at', { withTimezone: true }).notNull().defaultNow(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
});

// ── Meetings ─────────────────────────────────────────────────────────────
export const meetings = pgTable('meetings', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspaceId: uuid('workspace_id')
    .notNull()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  leadId: uuid('lead_id')
    .notNull()
    .references(() => leads.id, { onDelete: 'cascade' }),
  googleEventId: text('google_event_id'),
  meetLink: text('meet_link'),
  startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
  endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
  agenda: text('agenda'),
  preBrief: text('pre_brief'),
  postNotes: text('post_notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Knowledge Chunks ─────────────────────────────────────────────────────
// Vector dimension 384 matches Xenova/multilingual-e5-small.
export const knowledgeChunks = pgTable('knowledge_chunks', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspaceId: uuid('workspace_id')
    .notNull()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  section: text('section').notNull(),
  version: text('version').notNull(),
  content: text('content').notNull(),
  embedding: vector('embedding', { dimensions: 384 }).notNull(),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
// NOTE: ivfflat index must be added by raw SQL in the first migration:
//   CREATE INDEX knowledge_chunks_embedding_idx ON knowledge_chunks
//     USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

// ── KB Ingest Log ────────────────────────────────────────────────────────
// One row per (workspace, source). The current `contentSha256` lets the
// next ingest detect a changed source file and replace its chunks atomically
// without leaving stale content behind. `source = '__bootstrap__'` is the
// first-boot sentinel.
// ── Invite Links ─────────────────────────────────────────────────────────
// Public-route deal-scoping (rules #8, #9). Replaces the workspaces.default
// fallback. The HMAC-signed cookie payload includes dealId so every public
// API can resolve (workspace, deal, lead, investor) without a DB lookup.
export const inviteLinks = pgTable(
  'invite_links',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    dealId: uuid('deal_id')
      .notNull()
      .references(() => deals.id, { onDelete: 'cascade' }),
    investorId: uuid('investor_id')
      .notNull()
      .references(() => investors.id, { onDelete: 'cascade' }),
    leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
    token: text('token').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tokenUnique: uniqueIndex('invite_links_token_idx').on(t.token),
    investorActiveIdx: index('invite_links_investor_idx').on(t.workspaceId, t.investorId),
  }),
);

export const kbIngestLog = pgTable(
  'kb_ingest_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    source: text('source').notNull(),
    section: text('section').notNull(),
    contentSha256: text('content_sha256').notNull(),
    chunkCount: integer('chunk_count').notNull().default(0),
    ingestedAt: timestamp('ingested_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    sourceUnique: uniqueIndex('kb_ingest_log_source_idx').on(t.workspaceId, t.source),
  }),
);

// ── AI Logs ──────────────────────────────────────────────────────────────
export const aiLogs = pgTable(
  'ai_logs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    agent: aiAgentEnum('agent').notNull(),
    model: text('model').notNull(),
    promptHash: text('prompt_hash').notNull(),
    promptVersion: text('prompt_version').notNull(),
    inputTokens: integer('input_tokens').notNull(),
    outputTokens: integer('output_tokens').notNull(),
    usdCost: integer('usd_cost').notNull(), // store as micro-dollars (USD * 1_000_000) for precision
    latencyMs: integer('latency_ms').notNull(),
    outcome: aiOutcomeEnum('outcome').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    spendIdx: index('ai_logs_spend_idx').on(t.workspaceId, t.createdAt),
  }),
);

// ── Audit Events ─────────────────────────────────────────────────────────
export const auditEvents = pgTable(
  'audit_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    actorUserId: uuid('actor_user_id').references(() => users.id),
    action: text('action').notNull(),
    targetType: text('target_type'),
    targetId: text('target_id'),
    payload: jsonb('payload').notNull().default({}),
    ip: text('ip'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    feedIdx: index('audit_events_feed_idx').on(t.workspaceId, t.createdAt),
  }),
);

// ── Google OAuth tokens ──────────────────────────────────────────────────
// Stores OAuth tokens per founder/user for Google Calendar event creation.
// One row per (workspace, user); refreshed on each use.
export const googleOauthTokens = pgTable(
  'google_oauth_tokens',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token').notNull(),
    refreshToken: text('refresh_token'),
    scope: text('scope').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    calendarId: text('calendar_id').notNull().default('primary'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    lookupIdx: index('google_oauth_tokens_lookup_idx').on(t.workspaceId, t.userId),
  }),
);

// ── Magic-link revocations ───────────────────────────────────────────────
// Stateless HMAC tokens can't carry a revoked bit, so we record a "revoked
// before <ts>" cutoff per investor. verifyInvestorLink consults this on
// every request and rejects tokens with issuedAt earlier than the cutoff.
export const investorLinkRevocations = pgTable(
  'investor_link_revocations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    investorId: uuid('investor_id')
      .notNull()
      .references(() => investors.id, { onDelete: 'cascade' }),
    revokedBefore: timestamp('revoked_before', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }).notNull().defaultNow(),
    revokedBy: uuid('revoked_by').references(() => users.id),
    reason: text('reason'),
  },
  (t) => ({
    lookupIdx: index('investor_link_revocations_lookup_idx').on(t.workspaceId, t.investorId),
  }),
);

// ── Rate Limits ──────────────────────────────────────────────────────────
export const rateLimits = pgTable('rate_limits', {
  key: text('key').primaryKey(),
  tokens: integer('tokens').notNull(),
  refilledAt: timestamp('refilled_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Email Outbox ─────────────────────────────────────────────────────────
export const emailOutbox = pgTable(
  'email_outbox',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    toEmail: text('to_email').notNull(),
    subject: text('subject').notNull(),
    bodyText: text('body_text').notNull(),
    bodyHtml: text('body_html'),
    status: emailOutboxStatusEnum('status').notNull().default('draft'),
    attempts: integer('attempts').notNull().default(0),
    lastError: text('last_error'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    // Human-approval gate (rule #11). send route rejects unless status='approved'.
    approvedBy: uuid('approved_by').references(() => users.id),
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    // Optional FK to a lead so we can enforce rule #3 (no outreach without a lead).
    leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
    /** Drip cadence support — set to a future timestamp to defer dispatch. */
    scheduledFor: timestamp('scheduled_for', { withTimezone: true }),
    /** Groups multi-step cadences so a reply can cancel the rest. */
    cadenceGroupId: uuid('cadence_group_id'),
    /** 0-indexed position in the cadence; null for one-shot sends. */
    stepIndex: integer('step_index'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    drainIdx: index('email_outbox_drain_idx').on(t.status, t.createdAt),
  }),
);

// ── Email Inbox ──────────────────────────────────────────────────────────
export const emailInbox = pgTable('email_inbox', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspaceId: uuid('workspace_id')
    .notNull()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  imapUid: integer('imap_uid').notNull(),
  fromEmail: text('from_email').notNull(),
  subject: text('subject').notNull(),
  bodyText: text('body_text').notNull(),
  bodyHtml: text('body_html'),
  receivedAt: timestamp('received_at', { withTimezone: true }).notNull(),
  matchedLeadId: uuid('matched_lead_id').references(() => leads.id),
  processedAt: timestamp('processed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Stored Files (Postgres file storage backend) ──────────────────────────
export const storedFiles = pgTable('stored_files', {
  storageKey: text('storage_key').primaryKey(),
  contentType: text('content_type').notNull(),
  sizeBytesOriginal: integer('size_bytes_original').notNull(),
  sizeBytesCompressed: integer('size_bytes_compressed').notNull(),
  content: bytea('content').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
