#!/usr/bin/env bash
# test-pdf.sh - Generates a sample NDA PDF using pdf-lib and verifies it parses.
# Writes to a cwd-relative path so the test works on both POSIX and Git Bash on Windows
# (where /tmp resolves differently for the shell and Node.exe).
set -uo pipefail

OUT="./ootaos-nda-test.pdf"

cat <<JS | node
const { PDFDocument, StandardFonts, rgb, degrees } = require('pdf-lib');
const fs = require('fs');
(async () => {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const page = pdf.addPage([612, 792]);
  page.drawText('OotaOS — Mutual Non-Disclosure Agreement', { x: 50, y: 740, size: 16, font: bold });
  page.drawText('This is a test NDA generated by gate-03-integrations.', { x: 50, y: 700, size: 11, font });

  page.drawText('Test Investor', { x: 200, y: 400, size: 36, font, color: rgb(0.85,0.85,0.85), opacity: 0.3, rotate: degrees(45) });

  const audit = pdf.addPage([612, 792]);
  audit.drawText('Signature Audit Trail', { x: 50, y: 740, size: 16, font: bold });
  let y = 700;
  for (const [k,v] of [['Signer','Test Investor'],['Email','test@ootaos.com'],['IP','127.0.0.1'],['Signed at',new Date().toISOString()],['Template version','test-1.0.0']]) {
    audit.drawText(k+': '+v, { x: 50, y, size: 11, font });
    y -= 20;
  }

  const bytes = await pdf.save();
  fs.writeFileSync('$OUT', bytes);
  console.log('Wrote', '$OUT', bytes.length, 'bytes');
})();
JS

if [ ! -f "$OUT" ]; then echo "FAIL: $OUT not created"; exit 1; fi
if ! head -c 4 "$OUT" | grep -q '%PDF'; then echo "FAIL: not a PDF (missing %PDF magic)"; exit 1; fi
SIZE=$(wc -c < "$OUT")
[ "$SIZE" -gt 1000 ] || { echo "FAIL: PDF too small: $SIZE bytes"; exit 1; }
rm -f "$OUT"
echo "OK: PDF generated and valid ($SIZE bytes)"
